version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  pqr:
    build:
      context: ./pqr
    environment:
      FLASK_ENV: development
      IS_FAILING_SERVICE: "True"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    ports:
      - "5001:5000"
    depends_on:
      - rabbitmq

  monitor:
    build:
      context: ./monitor
    environment:
      CHECK_INTERVAL: 10
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    depends_on:
      - pqr
      - rabbitmq

  api_gateway:
    build:
      context: ./api_gateway
    environment:
      FLASK_ENV: development
      VALIDATOR_URL: validator:5010
      PQR_SERVICE_URL: pqr:5000
    ports:
      - "5000:5000"
    depends_on:
      - validator
      - pqr

  validator:
    build:
      context: ./validator
    environment:
      FLASK_ENV: development
      SECRET_KEY: secret_key
    ports:
      - "5010:5010"
    depends_on:
      - rabbitmq
