version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  pqr:
    build:
      context: ./pqr
    environment:
      - FLASK_ENV=development
      - IS_FAILING_SERVICE=True
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq

  monitor:
    build:
      context: ./monitor
    environment:
      - SERVICE_URLS=http://pqr:5000/pqrs
      - CHECK_INTERVAL=10
    depends_on:
      - pqr
      - rabbitmq
